# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('course_title', models.CharField(max_length=255)),
                ('course_description', models.TextField()),
                ('cs_area', models.CharField(choices=[('NONE', 'n/a'), ('ANALYSIS', 'Analysis'), ('APPLICATIONS', 'Applications'), ('SYSTEMS', 'Systems')], max_length=12)),
                ('course_instructor_last', models.CharField(max_length=255)),
                ('course_instructor_first', models.CharField(max_length=255)),
            ],
        ),
    ]
