# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0002_auto_20170801_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainformmodel',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='days_of_week',
            field=models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
