# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0004_auto_20170801_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainformmodel',
            name='days_of_week',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday')], max_length=1),
        ),
    ]
