# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0005_auto_20170801_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='mainformmodel',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='days_of_week',
            field=models.ManyToManyField(to='mainform.Days'),
        ),
    ]
