# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0007_auto_20170801_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainformmodel',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='is_friday',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='is_monday',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='is_thursday',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='is_tuesday',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='is_wednesday',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
