# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0008_auto_20170808_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainformmodel',
            name='course_instructor_first',
        ),
        migrations.RemoveField(
            model_name='mainformmodel',
            name='course_instructor_last',
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='course_instructor',
            field=models.CharField(choices=[('Ahmad, Yanif', 'Ahmad, Yanif')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
