# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0010_auto_20170808_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainformmodel',
            name='course_area',
            field=models.CharField(choices=[('NONE', 'n/a'), ('H', 'H'), ('E', 'E'), ('Q', 'Q'), ('NQ', 'NQ'), ('EQ', 'EQ')], default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='enrollment_limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='final_exam',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='num_credits',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainformmodel',
            name='semester',
            field=models.CharField(choices=[('F', 'Fall 2017'), ('S', 'Spring 2018')], default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
