# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0011_auto_20170808_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainformmodel',
            name='cs_area',
            field=models.CharField(blank=True, choices=[('', 'n/a'), ('ANALYSIS', 'Analysis'), ('APPLICATIONS', 'Applications'), ('SYSTEMS', 'Systems')], max_length=12),
        ),
        migrations.AlterField(
            model_name='mainformmodel',
            name='num_credits',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=4),
        ),
    ]
