# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0013_auto_20170814_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainformmodel',
            name='course_area',
            field=models.CharField(blank=True, choices=[('', 'n/a'), ('H', 'H'), ('E', 'E'), ('Q', 'Q'), ('NQ', 'NQ'), ('EQ', 'EQ')], max_length=4),
        ),
        migrations.AlterField(
            model_name='mainformmodel',
            name='num_credits',
            field=models.CharField(blank=True, choices=[('', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=4),
        ),
    ]
